const eventsApi = [
	{
		Name: 'Fiesta de Maxi',
		Image: 'foto.url',
		Location: 'Salta',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: 25,
		Category: ['Teatro'],
		City: 'capital',
		RedFlags: '1',
	},
	{
		Name: 'Carnaval de Rober',
		Image: 'foto.url',
		Location: 'Salta',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: ' 5',
		Category: ['Teatro'],
		City: 'capital',
		RedFlags: '1',
	},
	{
		Name: 'Cine de Cesar',
		Image: 'foto.url',
		Location: 'Salta',
		Price: '99999',
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: '25',
		Category: ['Teatro'],
		City: 'capital',
		RedFlags: 1,
	},
	{
		Name: 'Musical de Eliseo',
		Image: 'foto.url',
		Location: 'Salta',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: 25,
		Category: ['Teatro'],
		City: 'capital',
		RedFlags: 1,
	},
	{
		Name: 'Concierto de Sol',
		Image: 'foto.url',
		Location: 'Salta',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: 25,
		Category: ['Concierto'],
		City: 'capital',
		RedFlags: 1,
	},
	{
		Name: 'Obra de Eric',
		Image: 'foto.url',
		Location: 'Salta',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: 25,
		Category: ['Teatro'],
		City: 'capital',
		RedFlags: 1,
	},
	{
		Name: 'Circo de Jhonatan',
		Image: 'foto.url',
		Location: 'Peru',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: 25,
		Category: ['Recital'],
		City: 'capital',
		RedFlags: 1,
	},
	{
		Name: 'Toreno de E-Sports',
		Image: 'foto.url',
		Location: 'Salta',
		Price: 99999,
		Quantity: 10,
		Rating: 1002,
		Restrictions: ['No se aceptan mascotas', 'No se acepta comida'],
		AgeRestriction: 25,
		Category: ['Teatro'],
		City: 'capital',
		RedFlags: 1,
	},
];
const userApi = [
	{
		Name: 'Maxi',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'Guest',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'Capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '1',
		City: 'Salta',
	},
	{
		Name: 'Rober',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'User',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'Capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '2',
		City: 'Salta',
	},
	{
		Name: 'Cesar',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'Partner',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'Capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '3',
		City: 'Buenos Aires',
	},
	{
		Name: 'Sol',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'Admin',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'Capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '4',
		City: 'Buenos Aires',
	},
	{
		Name: 'Eliseo',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'Guest',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'Capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '5',
		City: 'Buenos Aires',
	},
	{
		Name: 'Eric',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'User',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'Capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '6',
		City: 'Buenos Aires',
	},
	{
		Name: 'Jhonatan',
		LoggedIn: false,
		Email: 'tuemail@gmail.com',
		Image: 'url',
		Role: 'Partner',
		Favourites: ['aca tendría que tener relación con la tabla de eventos'],
		Cart: ['aca tendría que tener relación con la tabla de eventos'],
		Location: 'capital',
		CreatedEvents: ['aca tendría que tener relación con la tabla de eventos'],
		RedFlags: '7',
		City: 'Lima',
	},
];
module.exports = { eventsApi, userApi };
